### PR TITLE
Use C++11 ranged for-loops where possible

### PR DESCRIPTION
**Pull request by r-barnes**
This uses C++11 ranged for-loops when possible to simply the code and make it clearer when iterators are needed and not.

I wasn't sure how to build the code, so I couldn't directly test this.

### CODE REVIEW

**Comment by expipiplus1** [comment]
> I wasn't sure how to build the code, so I couldn't directly test this.

Purely out of interest, what motivated you to do this if you aren't using this code?

**Comment by r-barnes** [comment]
My apologies. Vulkan is used within PyTorch, where I've been working on increasing code safety via this loop transformation. I'll close this.

**Comment by r-barnes** [comment]
@expipiplus1 : Vulkan is used in PyTorch. I've been trying to improve code safety/modernity there and like to upstream that.

When following the build directions for this repo I see the following when running `cmake`:
```
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
```
which currently prevents me from checking compilation on this code.

**Comment by adam-sawicki-a** [comment]
I introduced usage for range-based for loops wherever I could. Thank you for this suggestion and sorry it took so long.

Not every place could use this form as sometimes direct access to the iterator is needed.

**Pull request closed without merging**
