### PR TITLE
Fix for ABI interop (without VK_KHR_external_memory_win32)

### PR DESCRIPTION
**Pull request by Agrael1**

### CODE REVIEW

**Comment by GamesTrap** [comment]
I've just hit this problem in my CI/CD pipeline on Linux with GCC 13 & Clang 17.

Compiler logs: https://github.com/GamesTrap/TRAP/actions/runs/10655546793?pr=393

**Comment by Agrael1** [comment]
Yep, waiting for almighty creator :)

**Comment by Agrael1** [comment]
I also have the API that's waiting linux fix
https://github.com/Agrael1/Wisdom/actions/runs/10638479781

**Comment by adam-sawicki-a** [comment]
Thank you for this fix.

**Pull request merged**
