### PR TITLE
First example of xml file

### PR DESCRIPTION
**Pull request by realitix**
Hello @adam-sawicki-amd,

It's a work in progress.
I would like to get your opinion about it. It's how I see the xml file.

Thanks,
Jean-Sébastien

### CODE REVIEW

**Comment by adam-sawicki-amd** [comment]
What format is this? Is it some standard format documented somewhere, or your own?

This library has interface in similar style as Vulkan, so XML description could also be similar I guess. Feel free to use whatever works.

Providing bindings for programming languages other than C/C++ is out of scope of this project.

**Comment by realitix** [comment]
I followed the Vulkan XML file standard.
Of course providing binding is not in the scope of this project but providing a XML file may be.
It depends on you. Do you thinks it worses it ?

**Comment by adam-sawicki-amd** [comment]
I'm sorry but we don't want this XML file to become part of this repository because we may not be able to maintain it. We would prefer it to be in a separate repository.

**Comment by realitix** [comment]
No problem @adam-sawicki-amd

**Pull request closed without merging**
