### PR TITLE
docs: Fixed typo under 'Selecting Vulkan version' doc section

### PR DESCRIPTION
**Pull request by Max-Rodriguez**
Just a small grammar correction! Found it while I was reading the quick start guide :)

### CODE REVIEW

**Comment by adam-sawicki-a** [comment]
HTML documentation is generated automatically by Doxygen tool from special comments inside file vk_mem_alloc.h. We should not modify those HTML files as they will be overwritten anyway next time the documentation is generated. It should be fixed in vk_mem_alloc.h.

**Comment by Max-Rodriguez** [comment]
> HTML documentation is generated automatically by Doxygen tool from special comments inside file vk_mem_alloc.h. We should not modify those HTML files as they will be overwritten anyway next time the documentation is generated. It should be fixed in vk_mem_alloc.h.

Oh gotcha 👍 Will correct the commit in a couple hours

**Comment by Max-Rodriguez** [comment]
I've updated the branch to make the typo fix at the header file

**Comment by adam-sawicki-a** [comment]
Thank you for this contribution.

**Pull request merged**
