### PR TITLE
Minor CMake cleanup

### PR DESCRIPTION
**Pull request by juan-lunarg**
Broken up into 3 atomic commits

### CODE REVIEW

**Comment by adam-sawicki-a** [comment]
What is the minimum Cmake version supporting `MSVC_IDE`?

**Comment by adam-sawicki-a** [comment]
Cmake documentation says:
> Set to true when the target platform is the Microsoft Visual C++ IDE, as opposed to the command line compiler.

Is this intended that the settings you propose to put unde `MSVC_IDE` would work only with this variable set? What if the user wants to use MSVC command line compiler? Then, I guess they wouldn't be applied?

**Comment by juan-lunarg** [comment]
> What is the minimum CMake version supporting `MSVC_IDE`?

It's supported by 3.9, this is an old variable.

**Comment by juan-lunarg** [comment]
> Is this intended that the settings you propose to put unde `MSVC_IDE` would work only with this variable set? What if the user wants to use MSVC command line compiler? Then, I guess they wouldn't be applied?

My intent was to match the existing code. I've updated the code so it's friendlier to Ninja using MSVC.

**Comment by adam-sawicki-a** [comment]
Thank you very much for this contribution!

**Pull request merged**
